general:
  modality: monuseg 
  corr_mode: sdf # sdf, binary
  img_cond: 1 # condition on image to obtain segmentation mask
  data_path: "" # TODO: adapt data path
  csv_train: "train.csv"
  csv_test: "test.csv" # test256, test, test_orig
  batch_size: 4 
  sz: 128 
  resume_training: False
  load_path: ''
  resume_model_dir: 'models' 
  resume_cp: None # None or specific cp 
  class_label_cond: False 
  num_classes: 0
  with_class_label_emb: False

model:
  n_cin: 1 # 1, n_classes for multi-class segmentation
  n_fm: 128  '
  mults:
    - 1
    - 1
    - 2
    - 2
    - 4
    - 4

learning:
  epochs: 500000
  lr: 1.0E-4
  n_val: 8
  ema_decay: 0.999
  clip: 1. # or set to None else
  gpus:
    - 1

fm:
  type: 'ot'
  sigma_min: 1.0E-5

inference:
  latest: False
  load_exp: '' 
  load_model_dir: 'models' 
  load_cp: None # None or specific cp
  n_samples: 4 
  ode_steps: 4 # NFE
  thresh: 1.0E-2 # threshold to get binary from SDF
  n_eval: 1 
  merge_overlap: True 
